const nomineeInfo = [
    {
        panoImage: "obama-chats-with-justices",
        panoAlt: "Barack Obama chats with Supreme Court justices",
        scene: 0,
        headline: "Obama and the Justices",
        paragraph: [
            "As a Senator from Illinois and 44th President,",
            "Barack Obama worked to shape the Supreme Court.",
            "He both won and lost along the way. Photo: Pete Souza.",
        ].join(" "),
        thumbImage: "barack-obama-portrait",
        thumbAlt: "portrait photo of Barack Obama as Senator",
    },
    {
        panoImage: "john-roberts-sworn-in",
        panoAlt: "John Roberts sworn in as a Supreme Court justice",
        scene: 1,
        headline: "John Roberts",
        paragraph: [
            "In 2005, Senator Obama opposes George W. Bush's",
            "Supreme Court nominee John Roberts. Roberts is confirmed anyway",
            "and later becomes Chief Justice. Photo: Paul Morse.",
        ].join(" "),
        thumbImage: "john-roberts-portrait",
        thumbAlt: "portrait photo of John Roberts",
    },
    {
        panoImage: "bush-nominates-samuel-alito",
        panoAlt: "George Bush with Samuel Alito at his nomination announcement",
        scene: 2,
        headline: "Samuel Alito",
        paragraph: [
            "In 2006, Senator Obama opposes Bush's next Supreme Court nominee,",
            "Samuel Alito. Like Roberts, Alito is also confirmed.",
            "Photo: Paul Morse.",
        ].join(" "),
        thumbImage: "samuel-alito-portrait",
        thumbAlt: "portrait photo of Samuel Alito",
    },
    {
        panoImage: "obama-biden-meet-sotamayor",
        panoAlt: "Barack Obama and Joe Biden interview Sonia Sotomayor",
        scene: 3,
        headline: "Sonia Sotomayor",
        paragraph: [
            "In May 2009, now President Obama nominates Sonia Sotomayor",
            "of the US Court of Appeals for the Second Circuit.",
            "She is confirmed and replaces retiring Justice David H. Souter.",
            "Sotomayor was among four finalists; all women.",
            "Photo: Pete Souza.",
        ].join(" "),
        thumbImage: "sonia-sotamayor-portrait",
        thumbAlt: "portrait photo of Sonia Sotomayor",
    },
    {
        panoImage: "obama-meets-kagan",
        panoAlt: "Barack Obama interviews Elena Kagan",
        scene: 4,
        headline: "Elena Kagan",
        paragraph: [
            "In May 2010, President Obama nominates Elena Kagan,",
            "the Solicitor General of the United States.",
            "She is confirmed and replaces retiring Justice John Paul Stevens.",
            "Kagan was a candidate to replace Justice Souter in 2009.",
            "Photo: Pete Souza.",
        ].join(" "),
        thumbImage: "elena-kagan-portrait",
        thumbAlt: "portrait photo of Elena Kagan",
    },
    {
        panoImage: "antonin-scalia-smiles",
        panoAlt: "Antonin Scalia smiles",
        scene: 5,
        headline: "Antonin Scalia",
        paragraph: [
            "In February of 2016, Justice Antonin Scalia is found dead",
            "while vacationing at Cibolo Creek Ranch near Marfa, Texas.",
            "Photo: Stephen Masker.",
        ].join(" "),
        thumbImage: "antonin-scalia-portrait",
        thumbAlt: "portrait photo of Antonin Scalia",
    },
    {
        panoImage: "obama-biden-nominate-garland",
        panoAlt: "Obama and Biden with Garland at his nomination announcement",
        scene: 6,
        headline: "Merrick Garland",
        paragraph: [
            "In March, Obama nominates Merrick Garland,",
            "Chief Judge of the US Court of Appeals",
            "for the District of Columbia Circuit.",
            "Photo: Pete Souza.",
        ].join(" "),
        thumbImage: "merrick-garland-portrait",
        thumbAlt: "portrait photo of Merrick Garland",
    },
    {
        panoImage: "us-capitol-building",
        panoAlt: "exterior of the United States Capitol building",
        scene: 7,
        headline: "Mitch McConnell",
        paragraph: [
            "But Senate Majority Leader Mitch McConnell refuses to hold",
            "a confirmation hearing,",
            "citing Obama's final year in office.",
            "Judge Garland's nomination remains open for 293 days.",
            "expiring on January 3, 2017, as the 114th Congress closes.",
            "Photo: Greg Willis.",
        ].join(" "),
        thumbImage: "mitch-mcconnell-portrait",
        thumbAlt: "portrait photo of Mitch McConnell",
    },
    {
        panoImage: "trump-nominates-gorsuch",
        panoAlt: "Trump with Neil Gorsuch at his nomination announcement",
        scene: 8,
        headline: "Neil Gorsuch",
        paragraph: [
            "Donald Trump wins and nominates Judge Neil Gorsuch",
            "of the U.S. Court of Appeals for the Tenth Circuit.",
            "Gorsuch is confirmed by a vote of 54–45",
            "and assumes Justice Scalia's position in April 2017.",
            "Photo: White House staff.",
        ].join(" "),
        thumbImage: "neil-gorsuch-portrait",
        thumbAlt: "portrait photo of Neil Gorsuch",
    },
    {
        panoImage: "obama-congratulates-kagan",
        panoAlt: "Obama embraces Kagan in Oval Office and she is confirmed",
        scene: 9,
        headline: "Additional Photographs",
        paragraph: [
            "(A) Judicial portraits: Steve Petteway;",
            "except Justice Gorsuch: Franz Jantzen, and",
            "Judge Garland: US Court of Appeals for the DC Circuit.",
            "(B) Portrait of Senator McConnell: his staff.",
            "(C) Portrait of Barack Obama: Pete Souza.",
            "(D) Above: Obama congratulates a confirmed Elena Kagan.",
            "Photo: Pete Souza.",
        ].join(" "),
        thumbImage: "transparent-image",
        thumbAlt: "portrait photo of Barack Obama as President",
    },
];

export {nomineeInfo};